[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.dependencies]
serde = { version = "1.0.228", features = ["derive"] }
sqlx = { version = "0.8", features = ["runtime-tokio", "sqlite"] }
thiserror = { version = "2.0.18" }
tokio = { version = "1", features = ["full"] }
toml = { version = "1.1.2+spec-1.1.0" }
